# learn and study
# kongque
# 04/05/2011 add target SimpleFactory
SimpleFactory: SimpleFactory.cpp SimpleFactory.h main.cpp 
	g++ -o SimpleFactory SimpleFactory.cpp main.cpp

clean:
	rm SimpleFactory
