# learn and study
# kongque
# 04/05/2011 add target SimpleFactory
dp: SimpleFactory.cpp SimpleFactory.h \
	Factory.cpp Factory.h \
	AbstractFactory.cpp AbstractFactory.h \
	main.cpp 
	g++ -o dp SimpleFactory.cpp \
		Factory.cpp \
		AbstractFactory.cpp \
		main.cpp

clean:
	rm dp 
